### CREATE POLL

POST http://localhost:3000/polls
Content-Type: application/json

{
    "title": "Best CPU Brand?",
    "options": ["Intel","AMD"]
}

### GET POLL BY ID
 
GET http://localhost:3000/polls/668c9579-ed93-412f-8f71-036611d23d2c

### VOTE ON POLL (/polls/:pollId/votes)
# body: pollOptionId

POST http://localhost:3000/polls/668c9579-ed93-412f-8f71-036611d23d2c/votes
Content-Type: application/json

{
    "pollOptionId": "20d9afd9-e45a-4e5c-9c3b-13ac882f82a7"
}