### CREATE POLL

POST http://localhost:3000/polls
Content-Type: application/json

{
    "title": "Best CPU Brand?",
    "options": ["Intel","AMD"]
}

### GET POLL BY ID
 
GET http://localhost:3000/polls/02a5856a-9c3c-4f02-8bc6-148616d89fe0

### VOTE ON POLL (/polls/:pollId/votes)
# body: pollOptionId

POST http://localhost:3000/polls/02a5856a-9c3c-4f02-8bc6-148616d89fe0/votes
Content-Type: application/json

{
    "pollOptionId": "4d6b5105-8aec-4859-a671-1a7adadcbc73"
}